<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2022/06/10 22:57:26
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 10,
  'app_max_jobs_on_category' => 20,
));
