<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2022/06/01 10:45:51

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
