<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2022/06/08 18:27:54
sfConfig::add(array(
  'mod_sfjobeetlanguage_enabled' => true,
  'mod_sfjobeetlanguage_view_class' => 'sfPHP',
));
