<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2022/06/11 18:47:06
sfConfig::add(array(
  'mod_sfjobeetlanguage_enabled' => true,
  'mod_sfjobeetlanguage_view_class' => 'sfPHP',
));
