<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2022/06/11 19:10:48
sfConfig::add(array(
  'mod_sfjobeetlanguage_enabled' => true,
  'mod_sfjobeetlanguage_view_class' => 'sfPHP',
));
