<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2022/06/07 15:37:55
sfConfig::add(array(
  'mod_sfjobeetlanguage_enabled' => true,
  'mod_sfjobeetlanguage_view_class' => 'sfPHP',
));
