<?php
// auto-generated by sfCacheConfigHandler
// date: 2022/06/07 15:37:55
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

