<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2022/06/11 19:12:13
sfConfig::add(array(
  'mod_sfjobeetaffiliate_enabled' => true,
  'mod_sfjobeetaffiliate_view_class' => 'sfPHP',
));
